kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "f5-ai-security.fullname" . }}
  labels:
    {{- include "f5-ai-security.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "f5-ai-security.fullname" . }}
    weight: 100
  port:
    targetPort: {{ .Values.service.port }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
  alternateBackends: []
