apiVersion: v2
name: f5-ai-security
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: pgvector
    version: 0.1.0
    repository: https://rh-ai-quickstart.github.io/ai-architecture-charts
  - name: llm-service
    version: 0.5.2
    repository: https://rh-ai-quickstart.github.io/ai-architecture-charts
  - name: llama-stack
    version: 0.5.2
    repository: https://rh-ai-quickstart.github.io/ai-architecture-charts
